# Use with 'docker compose up'

version: '3'

services:
  expiration-reminder:
    image: expiration-reminder:latest
    container_name: expiration-reminder
    ports:
      - "5000:5000"
    volumes:
      - expiration-reminder-storage:/storage
    restart: always

volumes:
  expiration-reminder-storage:
