"""added date_wasted

Revision ID: 16e4cc95b53f
Revises: cec959c7dbdc
Create Date: 2023-09-01 16:53:21.673212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e4cc95b53f'
down_revision = 'cec959c7dbdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_wasted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('date_wasted')

    # ### end Alembic commands ###
