"""empty message

Revision ID: 23f26a290657
Revises: f7420df96825
Create Date: 2023-09-12 23:10:29.903064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f26a290657'
down_revision = 'f7420df96825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barcode', schema=None) as batch_op:
        batch_op.alter_column('barcode_value',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barcode', schema=None) as batch_op:
        batch_op.alter_column('barcode_value',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
