"""empty message

Revision ID: 7210fc8567ce
Revises: 
Create Date: 2023-09-07 21:49:45.595256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7210fc8567ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode_value', sa.String(length=100), nullable=False),
    sa.Column('barcode_item_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode_value')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_wasted', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('expiration_status', sa.Boolean(), nullable=True),
    sa.Column('wasted_status', sa.Boolean(), nullable=True),
    sa.Column('barcode_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barcode_id'], ['barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('barcode')
    # ### end Alembic commands ###
