name: Backend Check

on:
  push:
    branches: [ main, release ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main, release ]
    paths:
      - 'backend/**'

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: backend/requirements.txt
    
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 mypy pytest
    - name: Lint with flake8
      working-directory: ./backend
      run: |
        ./run_tests.sh --basic-flake8
        ./run_tests.sh --complex-flake8
    
    - name: Check types with mypy
      working-directory: ./backend
      run: |
        ./run_tests.sh --mypy
        
    - name: Build Docker image
      working-directory: ./backend
      run: |
        docker build -t expiration-reminder-backend . 
