name: Deploy Backend to Google Cloud Run

on:
  workflow_run:
    workflows: ["Backend Check"]
    branches:
      - release
    types:
      - completed

env:
  PROJECT_ID: pantryguardian-f8381
  SERVICE_NAME: expiration-reminder
  REGION: us-central1  # You may want to adjust this based on your needs

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/105128604631/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: pg-service-account@pantryguardian-f8381.iam.gserviceaccount.com

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy to Cloud Run
      run: |
        cd backend
        gcloud run deploy expiration-reminder \
          --source . \
          --service-account=pg-service-account@pantryguardian-f8381.iam.gserviceaccount.com \
          --max-instances=1 \
          --port=5000 \
          --region=us-central1 \
          --set-env-vars=GIT_HASH=${{ github.sha }} \
          --quiet 