import React, { useState, useEffect } from 'react';
import { View, TouchableWithoutFeedback } from 'react-native';
import { Button, Modal as PaperModal, TextInput as PaperTextInput } from 'react-native-paper';
import { Calendar } from 'react-native-calendars';
import { Picker } from '@react-native-picker/picker';
import GlobalStyles from './GlobalStyles';
import { colors } from './theme';
import Requests from './Requests';
import axios from 'axios';

interface AddProductModalProps {
  visible: boolean;
  onClose: () => void;
  onProductAdded: () => void;
}

const BASE_URL = "http://127.0.0.1:8081";

const AddProductModal: React.FC<AddProductModalProps> = ({ visible, onClose, onProductAdded }) => {
  const [productName, setProductName] = useState('');
  const [expirationDate, setExpirationDate] = useState('');
  const [location, setLocation] = useState('');
  const [category, setCategory] = useState('');
  const [isDatePickerVisible, setIsDatePickerVisible] = useState(false);
  const [locationModalVisible, setLocationModalVisible] = useState(false);
  const [categoryModalVisible, setCategoryModalVisible] = useState(false);
  const [locations, setLocations] = useState<string[]>([]);
  const [categories, setCategories] = useState<string[]>([]);

  useEffect(() => {
    const loadLocationsAndCategories = async () => {
      if (!Requests.idToken) return;  // Ensure token is available before making requests
  
      try {
        const response = await axios.get(`${BASE_URL}/get_locations_categories`, {
          headers: { 'idToken': Requests.idToken }
        });
        if (response.status === 200) {
          setLocations(response.data.locations);
          setCategories(response.data.categories);
        }
      } catch (error) {
        console.error('Failed to load locations and categories', error);
      }
    };
  
    loadLocationsAndCategories();
  }, []);
  

  const handleExpirationDateChange = (date: string) => {
    setExpirationDate(date);
    setIsDatePickerVisible(false);
  };

  const handleExpirationDateFocus = () => {
    setIsDatePickerVisible(true);
  };

  const handleExpirationDateBlur = () => {
    setIsDatePickerVisible(false);
  };

  const handleLocationChange = (value: string) => {
    setLocation(value);
    setLocationModalVisible(false);
  };

  const handleCategoryChange = (value: string) => {
    setCategory(value);
    setCategoryModalVisible(false);
  };

  const handleAddProduct = async () => {
    const newProduct = {
      product_name: productName,
      expiration_date: expirationDate,
      location: location,
      category: category,
      barcode: '', // Assuming no barcode initially
      product_id: '', // Placeholder, it will be generated by the backend
      wasted: false, // Default value for new products
      creation_date: new Date().toISOString(), // Current date as creation date
    };

    const requests = new Requests();
    const success = await requests.addProduct(newProduct);
    if (success) {
      onProductAdded();
      onClose(); // Close the modal
      // Clear input fields
      setProductName('');
      setExpirationDate('');
      setLocation('');
      setCategory('');
    } else {
      console.error('Failed to add product');
    }
  };

  return (
    <PaperModal visible={visible} onDismiss={onClose} contentContainerStyle={GlobalStyles.modalContent}>
      <TouchableWithoutFeedback onPress={() => setIsDatePickerVisible(false)}>
        <View>
          <PaperTextInput
            style={GlobalStyles.input}
            mode="outlined"
            label="Enter the product name"
            value={productName}
            onChangeText={text => setProductName(text)}
          />
          <PaperTextInput
            style={GlobalStyles.input}
            mode="outlined"
            label="Expiration Date (MM/DD/YYYY)"
            value={expirationDate}
            onFocus={handleExpirationDateFocus}
            onBlur={handleExpirationDateBlur}
            onChangeText={text => setExpirationDate(text)}
          />
          <PaperTextInput style={GlobalStyles.input} mode="outlined" label="Barcode Number (optional)" />
          <Button theme={{ colors: { primary: colors.primary } }} onPress={() => setLocationModalVisible(true)}>
            {location ? 'Location: ' + location : 'Select Location'}
          </Button>
          <Button theme={{ colors: { primary: colors.primary } }} onPress={() => setCategoryModalVisible(true)}>
            {category ? 'Category: ' + category : 'Select Category'}
          </Button>
          <Button mode="contained" theme={{ colors: { primary: colors.primary } }} onPress={handleAddProduct}>
            Submit
          </Button>
          {isDatePickerVisible && <Calendar onDayPress={(day:any) => handleExpirationDateChange(day.dateString)} />}
          </View>
      </TouchableWithoutFeedback>

      <PaperModal visible={locationModalVisible} onDismiss={() => setLocationModalVisible(false)} contentContainerStyle={GlobalStyles.modalContent}>
        <View style={GlobalStyles.pickerContainer}>
          <Picker selectedValue={location} style={GlobalStyles.picker} onValueChange={handleLocationChange}>
            <Picker.Item label="Select Location" value="" />
            {locations.map((loc) => (
              <Picker.Item key={loc} label={loc} value={loc} />
            ))}
          </Picker>
        </View>
      </PaperModal>

      <PaperModal visible={categoryModalVisible} onDismiss={() => setCategoryModalVisible(false)} contentContainerStyle={GlobalStyles.modalContent}>
        <Picker selectedValue={category} style={GlobalStyles.input} onValueChange={(itemValue) => handleCategoryChange(itemValue)}>
          <Picker.Item label="Select Category" value="" />
          {categories.map((cat) => (
            <Picker.Item key={cat} label={cat} value={cat} />
          ))}
        </Picker>
      </PaperModal>
    </PaperModal>
  );
};

export default AddProductModal;
